//! Rates coverage report (Sections 3.2 and 13.5 of docs/plans/rates-from-data-plan.md). Everything in the report is computed from
//! the engine's data and what the network generator actually builds; no row, status or share is written by hand.
//!
//! * Section 1: the measured rows (used and held out) per template rule, and the held-out error of each rule.
//! * Section 2: a fixed list of bench experiments; for every reaction the engine generates for them, where its rate comes from
//!   (precedence 1 measured and read from its source, 2 relation with checked parameters, 3 rule or estimate, "uncited" and
//!   recalled values listed separately).
//! * Section 3: the inorganic rate data (electron transfer, ligand substitution, solid decomposition, heterogeneous
//!   catalysis) with the verification status of each row.
//! Writes `docs/plans/rates-coverage.md`. Run: cargo run --release --example rates_coverage

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::Path;

use reaction_chamber_engine::rate_data::{self, OrganicRate};
use reaction_chamber_engine::rate_harness;

#[derive(serde::Deserialize)]
struct Rows {
    organic: Vec<OrganicRate>,
}

fn rule_of(source: &str) -> String {
    source.split("/ rule '").nth(1).and_then(|s| s.split('\'').next()).unwrap_or("?").to_string()
}

/// What an organic rate comes from: (precedence, label).
fn classify(g: &reaction_chamber_engine::network_generator::GeneratedReaction) -> (u8, &'static str) {
    if g.rate_from_store {
        return (1, "measured, read from its source");
    }
    if g.template_source.contains("Mayr relation") {
        return (2, "Mayr relation (measured N, sN, E)");
    }
    let s = g.template_source.to_lowercase();
    if s.contains("fit to") && s.contains("verified rows") {
        (3, "rule fitted to verified rows")
    } else if s.contains("uncited") {
        (3, "UNCITED rule (speculative)")
    } else {
        (3, "rule from recalled literature values (estimated)")
    }
}

fn main() {
    rate_data::ensure_loaded();
    let manifest = env!("CARGO_MANIFEST_DIR");
    let used: Rows = serde_json::from_str(&std::fs::read_to_string(Path::new(manifest).join("data/rates_measured.json")).unwrap()).unwrap();
    let held: Rows = serde_json::from_str(&std::fs::read_to_string(Path::new(manifest).join("tests/fixtures/rates_held_out.json")).unwrap()).unwrap();
    let mut md = String::new();
    writeln!(md, "# Reaction rates coverage report\n").unwrap();
    writeln!(md, "Generated by `engine/examples/rates_coverage.rs` from the engine's own data and network generator; nothing in it is written by hand.").unwrap();
    writeln!(md, "Plan: `docs/plans/rates-from-data-plan.md` (sections 3.2, 6, 13.5). Re-run after any change of the data.\n").unwrap();

    // ---------------------------------------------------------------- section 1
    writeln!(md, "## 1. Measured organic rows and the rules they fit\n").unwrap();
    writeln!(md, "{} rows are used by the engine (read from their source), {} are held out (never loaded). Rows of the earlier table that were written from memory are not compiled (`pipeline/data/rates_unverified.csv`).\n", used.organic.len(), held.organic.len()).unwrap();
    let mut by_rule: BTreeMap<(String, String), (usize, Vec<f64>)> = BTreeMap::new();
    let mut unconnected = 0;
    for r in &used.organic {
        match rate_harness::find_reaction(&r.template, &r.reactants, &r.products, r.t_k, &r.solvent_class) {
            Some(g) => by_rule.entry((g.family_id.clone(), rule_of(&g.template_source))).or_default().0 += 1,
            None => unconnected += 1,
        }
    }
    for r in &held.organic {
        match rate_harness::find_reaction(&r.template, &r.reactants, &r.products, r.t_k, &r.solvent_class) {
            Some(g) => by_rule.entry((g.family_id.clone(), rule_of(&g.template_source))).or_default().1.push(r.k_m_s.log10() - rate_harness::rule_k(&g, r.t_k).log10()),
            None => unconnected += 1,
        }
    }
    writeln!(md, "| Template / rule | used rows | held-out rows | held-out rms (log10) | gate (rms <= 0.7) |").unwrap();
    writeln!(md, "|---|---|---|---|---|").unwrap();
    for ((family, rule), (n_used, errs)) in &by_rule {
        let rms = if errs.is_empty() { f64::NAN } else { (errs.iter().map(|e| e * e).sum::<f64>() / errs.len() as f64).sqrt() };
        let verdict = if errs.is_empty() { "no held-out row".to_string() } else if rms <= 0.7 { "met".to_string() } else { "NOT MET".to_string() };
        writeln!(md, "| {family} / {rule} | {n_used} | {} | {} | {verdict} |", errs.len(), if errs.is_empty() { "n/a".into() } else { format!("{rms:.2}") }).unwrap();
    }
    writeln!(md, "\nRows that do not connect to a generated reaction: {unconnected}.\n").unwrap();
    writeln!(md, "Caveat: structural features of the rules were added while looking at the held-out misfits, so the held-out errors are optimistic; they measure interpolation inside the compound classes the training rows cover.\n").unwrap();

    // ---------------------------------------------------------------- section 2
    writeln!(md, "## 2. Bench experiments: where each generated rate comes from\n").unwrap();
    // (name, template key for the medium, family expected, reactants, T, solvent class)
    let experiments: Vec<(&str, &str, &str, Vec<&str>, f64, &str)> = vec![
        ("Ester saponification: ethyl acetate + OH-", "base_ester_hydrolysis", "base_ester_hydrolysis", vec!["CC(=O)OCC", "[OH-]"], 298.15, "water"),
        ("Ester acid hydrolysis: methyl acetate", "acid_ester_hydrolysis_acid", "acid_ester_hydrolysis", vec!["CC(=O)OC"], 298.15, "water"),
        ("Phenyl acetate + OH-", "base_ester_hydrolysis", "base_ester_hydrolysis", vec!["CC(=O)Oc1ccccc1", "[OH-]"], 298.15, "water"),
        ("Amide acid hydrolysis: acetamide", "amide_hydrolysis_acid", "amide_hydrolysis", vec!["CC(N)=O"], 298.15, "water"),
        ("SN2: bromomethane + OH-", "sn2_substitution", "sn2_substitution", vec!["CBr", "[OH-]"], 298.15, "water"),
        ("SN2: 1-bromobutane + OH-", "sn2_substitution", "sn2_substitution", vec!["CCCCBr", "[OH-]"], 298.15, "water"),
        ("SN1: tert-butyl chloride in water", "sn1_solvolysis", "sn1_solvolysis", vec!["CC(C)(C)Cl"], 298.15, "water"),
        ("SN1: 2-bromopropane in water", "sn1_solvolysis", "sn1_solvolysis", vec!["CC(C)Br"], 298.15, "water"),
        ("Neutral hydrolysis: bromomethane", "halide_neutral_hydrolysis", "halide_neutral_hydrolysis", vec!["CBr"], 298.15, "water"),
        ("Neutral hydrolysis: benzyl chloride", "halide_neutral_hydrolysis", "halide_neutral_hydrolysis", vec!["ClCc1ccccc1"], 298.15, "water"),
        ("Menshutkin: bromomethane + trimethylamine", "menshutkin_alkylation", "menshutkin_alkylation", vec!["CBr", "CN(C)C"], 298.15, "water"),
        ("Michael addition: benzylidenemalononitrile + propylamine", "michael_addition", "michael_addition", vec!["N#CC(C#N)=Cc1ccccc1", "CCCN"], 293.15, "water"),
        ("Carbocation + water: bis(4-methoxyphenyl)methyl cation", "carbocation_trapping_by_solvent", "carbocation_trapping_by_solvent", vec!["[H][C+](c1ccc(OC)cc1)c1ccc(OC)cc1", "O"], 293.15, "water"),
        ("Aldol addition: acetaldehyde + acetaldehyde", "aldol_addition", "aldol_addition", vec!["CC=O"], 298.15, "water"),
        ("Carbonyl hydration: acetaldehyde", "carbonyl_hydration", "carbonyl_hydration", vec!["CC=O"], 298.15, "water"),
        ("Diels-Alder: butadiene + maleic anhydride", "diels_alder", "diels_alder", vec!["C=CC=C", "O=C1C=CC(=O)O1"], 298.15, "other"),
        ("Alkene hydration (acid): propene", "alkene_hydration_acid", "alkene_hydration", vec!["CC=C"], 298.15, "water"),
        ("Electrophilic bromination: benzene + Br2", "eas_halogenation", "eas_halogenation", vec!["c1ccccc1", "BrBr"], 298.15, "other"),
    ];
    writeln!(md, "| Experiment | Reaction generated | k at T (M^(1-n) s^-1) | Precedence | Source of the rate |").unwrap();
    writeln!(md, "|---|---|---|---|---|").unwrap();
    let (mut n_total, mut n_p12, mut n_uncited, mut n_missing) = (0, 0, 0, 0);
    for (name, key, family, reactants, t, class) in &experiments {
        let rs: Vec<String> = reactants.iter().map(|s| s.to_string()).collect();
        let gen: Vec<_> = rate_harness::generate(key, &rs, *t, class).into_iter().filter(|g| g.family_id == *family).collect();
        if gen.is_empty() {
            n_missing += 1;
            writeln!(md, "| {name} | NOT GENERATED | | | |").unwrap();
            continue;
        }
        for g in gen {
            let (prec, label) = classify(&g);
            n_total += 1;
            if prec <= 2 {
                n_p12 += 1;
            }
            if label.starts_with("UNCITED") {
                n_uncited += 1;
            }
            let mut prods: Vec<String> = g.products.keys().cloned().collect();
            prods.sort();
            writeln!(md, "| {name} | {} | {:.2e} | {prec} | {label} |", prods.join(" + "), rate_harness::engine_k(&g, *t)).unwrap();
        }
    }
    writeln!(md, "\nOrganic rate evaluations in the list: {n_total}; at precedence 1-2: {n_p12} ({:.0} %); on an uncited speculative rule: {n_uncited}; experiments the engine does not generate: {n_missing}.\n", 100.0 * n_p12 as f64 / n_total.max(1) as f64).unwrap();

    // ---------------------------------------------------------------- section 3
    writeln!(md, "## 3. Inorganic rate data and their verification\n").unwrap();
    let redox: Vec<_> = serde_json::from_str::<serde_json::Value>(&std::fs::read_to_string(Path::new(manifest).join("data/rates_measured.json")).unwrap()).unwrap()["redox"].as_array().unwrap().clone();
    let verified_redox = redox.iter().filter(|r| r["verification"] == "verified").count();
    writeln!(md, "**Measured electron-transfer laws** (`rates_measured.json`, `redox`): {} rows, {} read from their source, {} recalled (Speculative; they replace only the Marcus estimate).\n", redox.len(), verified_redox, redox.len() - verified_redox).unwrap();
    let rc: serde_json::Value = serde_json::from_str(&std::fs::read_to_string(Path::new(manifest).join("data/redox_couples.json")).unwrap()).unwrap();
    let couples = rc["couples"].as_array().unwrap();
    let measured_kinds = couples.iter().filter(|c| c["kind"] == "outer_sphere_measured").count();
    let checked = couples.iter().filter(|c| c["verification"].as_str().map_or(false, |v| v.starts_with("verified"))).count();
    writeln!(md, "**Self-exchange constants** (`redox_couples.json`): {} couples labelled outer-sphere, {} of them checked against a source (the Marcus cross relation is therefore run on recalled constants).\n", measured_kinds, checked).unwrap();
    let we: serde_json::Value = serde_json::from_str(&std::fs::read_to_string(Path::new(manifest).join("data/water_exchange.json")).unwrap()).unwrap();
    let ions = we["ions"].as_array().unwrap();
    let we_checked = ions.iter().filter(|r| r["verification"].as_str().map_or(false, |v| v.starts_with("verified"))).count();
    writeln!(md, "**Water-exchange rates** (`water_exchange.json`, Eigen-Wilkins): {} ions, {} with k_ex matching a published copy of the Helm & Merbach table, {} recalled. Activation enthalpies and mechanism labels are recalled for all.\n", ions.len(), we_checked, ions.len() - we_checked).unwrap();
    let eqs = reaction_chamber_engine::chem_db::get_default_equilibria();
    let slow: Vec<_> = eqs.iter().filter(|e| e.rate.as_ref().map_or(false, |r| r.first_step.is_some())).collect();
    writeln!(md, "Complexation rows of the default equilibria that are rate-limited by water exchange: {}", slow.len()).unwrap();
    for id in ["iron_thiocyanate", "copper_tetraammine", "co_cl_1"] {
        let row = eqs.iter().find(|e| e.id == id);
        writeln!(md, "- `{id}`: {}", match row.and_then(|e| e.rate.as_ref()) { Some(r) => format!("slow ({})", r.source), None => "instantaneous (labile ion)".to_string() }).unwrap();
    }
    writeln!(md, "\n**Solid thermal decompositions** (`solid_decomposition.json`):\n").unwrap();
    writeln!(md, "| Solid | catalyst | verification | stated onset (K) | T(5 %) at 10 K/min from the row's own A, Ea (K) |").unwrap();
    writeln!(md, "|---|---|---|---|---|").unwrap();
    for e in reaction_chamber_engine::gem::rates::solid_decomp_entries() {
        let beta = 10.0 / 60.0;
        let (mut t, mut integral, mut t5) = (250.0f64, 0.0f64, f64::NAN);
        while t < 2000.0 {
            integral += e.a * (-e.ea_j_mol / (reaction_chamber_engine::physics::R_GAS * t)).exp() * 0.05 / beta;
            t += 0.05;
            if 1.0 - (-integral).exp() >= 0.05 {
                t5 = t;
                break;
            }
        }
        writeln!(md, "| {} | {} | {} | {:.0} | {:.0} |", e.solid, e.catalyst.clone().unwrap_or_default(), e.verification.clone().unwrap_or("none".into()), e.onset_temp_k, t5).unwrap();
    }
    writeln!(md, "\n**Kinetic rows** (`core_reactions.json`): tier of each row's rate law.\n").unwrap();
    for k in reaction_chamber_engine::chem_db::get_default_kinetic_reactions() {
        writeln!(md, "- `{}`: tier {:?}", k.id, k.tier).unwrap();
    }

    let out = Path::new(manifest).join("../docs/plans/rates-coverage.md");
    std::fs::write(&out, md).unwrap();
    println!("wrote {} ({} organic evaluations, {} at precedence 1-2, {} uncited)", out.display(), n_total, n_p12, n_uncited);
}
