#!/usr/bin/env python3
"""Ion-size parameters (Debye-Hueckel / B-dot a, Angstrom) and standard partial molar volumes (cm3/mol) of aqueous ions
(X2 of docs/plans/data-acquisition-plan.md) -> engine/data/ion_data_tabulated.json.

  ion size a   : PHREEQC llnl.dat `-gamma a b` (Helgeson, Kirkham & Flowers 1981 / Truesdell & Jones 1974 ion-size
                 parameters of the B-dot model), then wateq4f.dat / minteq.v4.dat for ions llnl does not hold
  V0           : OBIGT (CHNOSZ) partial molar volume of the aqueous ion at 25 C and 1 bar (SUPCRT92 / Shock & Helgeson
                 1988 / later HKF compilations)

Ions the engine's species store holds (species_tabulated.json, species_inorganic.json, seed) are kept.
"""
import csv
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import parse_phreeqc_db as pp

ROOT = Path(__file__).resolve().parents[2]
RAW = ROOT / "pipeline" / "raw"
OUT = ROOT / "engine" / "data" / "ion_data_tabulated.json"


def num(v):
    try:
        return float(v)
    except (TypeError, ValueError):
        return None


def main():
    sizes = {}
    src_size = {}
    for fname, label in [("llnl.dat", "llnl.dat -gamma"), ("wateq4f.dat", "wateq4f.dat -gamma"), ("minteq.v4.dat", "minteq.v4.dat -gamma"), ("phreeqc.dat", "phreeqc.dat -gamma")]:
        text = (RAW / "phreeqc" / fname).read_text(errors="replace")
        db = pp.read(RAW / "phreeqc" / fname)
        for sp in db["species"]:
            n, g = sp["name"], sp["gamma"]
            if n and g and g[0] and re.search(r"[+-]\d*$", n) and n not in sizes and 0.5 <= g[0] <= 12:
                sizes[n] = g[0]
                src_size[n] = label
    vols = {}
    for fname in ["inorganic_aq.csv", "SLOP98-a.csv", "SLOP98-b.csv"]:
        for r in csv.DictReader(open(RAW / "obigt" / fname)):
            f, v = r["formula"], num(r["V"])
            if v is not None and f not in vols and re.search(r"[+-]\d*$", f):
                vols[f] = v
    tab = json.loads((ROOT / "engine" / "data" / "species_tabulated.json").read_text())
    held = {r["id"] for r in tab["rows"] if r["phase"] == "aq" and r["charge"] != 0}
    inorg = json.loads((ROOT / "engine" / "data" / "species_inorganic.json").read_text())
    held |= {r[0] for r in inorg["aq"] if r[2] != 0}
    held |= set(json.loads((ROOT / "engine" / "data" / "ion_interactions.json").read_text())["ion_size_angstrom"])
    seed = (ROOT / "engine" / "src" / "db" / "seed.rs").read_text()
    held |= {m.group(1) for m in re.finditer(r'make_aq\w*\("([^"]+)", "[^"]+", (-?\d+)', seed) if int(m.group(2)) != 0}
    out = {
        "comment": "Generated by pipeline/db/build_ion_data.py. ion_size_angstrom: B-dot ion-size parameter a (Helgeson, Kirkham & Flowers 1981; as tabulated in PHREEQC llnl.dat / wateq4f.dat / minteq.v4.dat); ion_volume_v0_cm3_mol: standard partial molar volume at 25 C (OBIGT, CHNOSZ: SUPCRT92 / Shock & Helgeson 1988). Tier Tabulated. Rows here replace those of ion_interactions.json.",
        "tier": "Tabulated",
        "ion_size_angstrom": {k: v for k, v in sorted(sizes.items()) if k in held},
        "ion_size_source": {k: src_size[k] for k in sorted(sizes) if k in held},
        "ion_volume_v0_cm3_mol": {k: round(v, 3) for k, v in sorted(vols.items()) if k in held},
    }
    OUT.write_text(json.dumps(out, indent=1) + "\n")
    old = json.loads((ROOT / "engine" / "data" / "ion_interactions.json").read_text())
    print("sizes:", len(out["ion_size_angstrom"]), "volumes:", len(out["ion_volume_v0_cm3_mol"]))
    for k, v in old["ion_size_angstrom"].items():
        if k in out["ion_size_angstrom"] and abs(out["ion_size_angstrom"][k] - v) > 0.01:
            print("  size differs", k, v, "->", out["ion_size_angstrom"][k])
    for k, v in old["ion_volume_v0_cm3_mol"].items():
        if k in out["ion_volume_v0_cm3_mol"] and abs(out["ion_volume_v0_cm3_mol"][k] - v) > 1.0:
            print("  V0 differs", k, v, "->", out["ion_volume_v0_cm3_mol"][k])


main()
