#!/usr/bin/env python3
"""Measured vapour pressures of pure liquids (ThermoML 'psat' category) -> engine/data/vapor_pressure_measured.json

For every compound (InChIKey) with at least 6 liquid-phase vapour-pressure measurements spanning 15 K or more, an Antoine fit
log10(P/Pa) = A - B / (T/K + C), robust (soft-L1) least squares on log P, C in [-120, 0].  The fit is kept when its rms residual is
below 0.04 in log10 (10 %).  The engine uses it between the lowest and highest measured temperature (+-5 K) and a Clausius-Clapeyron
extension with the slope at the end outside (`vle.rs`).  Recorded per compound: A, B, C, T_min, T_max, n points, n papers, rms.
"""
import json
import re
from collections import defaultdict
from pathlib import Path

import numpy as np
from scipy.optimize import least_squares

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "pipeline" / "cache" / "thermoml" / "psat.jsonl"
OUT = ROOT / "engine" / "data" / "vapor_pressure_measured.json"


def fit(T, logp):
    # initial guess: linear in 1/T
    k, b0 = np.polyfit(1.0 / T, logp, 1)
    best = None
    for c0 in (-40.0, -80.0, -10.0):
        p0 = [b0, -k - c0 * 0.0, c0]
        def res(p):
            a, b, c = p
            return a - b / (T + c) - logp
        r = least_squares(res, [b0 + 0.0, -k, c0], bounds=([-5, 0, -120], [30, 20000, 0]), loss="soft_l1", f_scale=0.03)
        rms = float(np.sqrt(np.mean(res(r.x) ** 2)))
        if best is None or rms < best[1]:
            best = (r.x, rms)
    return best


def main():
    by = defaultdict(list)
    names = {}
    for line in open(SRC):
        r = json.loads(line)
        if len(r["compounds"]) != 1 or r["phase"] != "Liquid" or r["T_K"] is None or r["value"] <= 0:
            continue
        c = r["compounds"][0]
        if not c.get("key") or not c.get("formula") or re.search(r"[+-]", c["formula"]):
            continue
        by[c["key"]].append((r["T_K"], r["value"] * 1000.0, r["doi"]))
        names[c["key"]] = c.get("name")
    out = {}
    skipped = 0
    for key, pts in by.items():
        T = np.array([p[0] for p in pts]); P = np.array([p[1] for p in pts])
        if len(pts) < 6 or T.max() - T.min() < 15 or P.min() < 1e-3 or P.max() > 4e6:
            continue
        # drop exact duplicates of (T, P) from the same paper
        (a, b, c), rms = fit(T, np.log10(P))
        if rms > 0.04:
            skipped += 1
            continue
        out[key] = {"a": round(float(a), 5), "b": round(float(b), 3), "c": round(float(c), 3), "t_min": round(float(T.min()), 2), "t_max": round(float(T.max()), 2),
                    "n": len(pts), "n_papers": len({p[2] for p in pts}), "rms_log10": round(rms, 4), "name": names[key]}
    doc = {"model": "Antoine log10(P/Pa) = a - b / (T/K + c) fitted to measured liquid vapour pressures; valid between t_min and t_max (the engine extends it with the slope at the end)",
           "tier": "tabulated",
           "source": "NIST/TRC ThermoML Archive (2020-09-30 snapshot): pure-liquid vapour-pressure measurements; one fit per InChIKey with >= 6 points spanning >= 15 K and rms <= 0.04 in log10. Generated by pipeline/db/build_vapor_pressure.py.",
           "compounds": dict(sorted(out.items()))}
    OUT.write_text(json.dumps(doc, indent=0) + "\n")
    print(len(out), "compounds fitted;", skipped, "rejected for rms > 0.04;", f"{OUT.stat().st_size/1e3:.0f} kB")


main()
