#!/usr/bin/env python3
"""Measured hydration free energies (FreeSolv v0.52, pipeline/data/hydration_dg_experimental.csv) keyed by the connectivity block of the
InChIKey -> engine/data/hydration_measured.json.  The engine uses a measured value instead of the group-additive estimate for the
aqueous standard state (and so the Henry constant) of a solute it finds in the table (hydration.rs `measured_kj`)."""
import csv
import json
from pathlib import Path

from rdkit import Chem, RDLogger
from rdkit.Chem import inchi

RDLogger.DisableLog("rdApp.*")
ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "pipeline" / "data" / "hydration_dg_experimental.csv"
OUT = ROOT / "engine" / "data" / "hydration_measured.json"

rows = [ln for ln in open(SRC) if ln.strip() and not ln.startswith("#")]
out, dup = {}, 0
for r in csv.DictReader(rows):
    m = Chem.MolFromSmiles(r["smiles"])
    if m is None:
        continue
    key = inchi.MolToInchiKey(m)
    if not key:
        continue
    block = key.split("-")[0]
    if block in out:
        dup += 1
        continue
    out[block] = {"dg_kcal_mol": float(r["dg_kcal_mol"]), "unc_kcal_mol": float(r["unc_kcal_mol"]), "name": r["name"], "doi": r["doi"]}
doc = {"model": "experimental hydration free energy, 1 M ideal gas -> 1 M ideal solution, 298 K, kcal/mol, by the first block (connectivity) of the InChIKey",
       "tier": "tabulated",
       "source": "FreeSolv v0.52 (Mobley & Guthrie, J. Comput.-Aided Mol. Des. 28 (2014) 711): experimental values with the DOI of the original measurement. Generated by pipeline/db/build_hydration_measured.py.",
       "compounds": dict(sorted(out.items()))}
OUT.write_text(json.dumps(doc, indent=0) + "\n")
print(len(out), "compounds,", dup, "duplicates skipped")
