#!/usr/bin/env python3
"""Display data of the molecular viewer (web/src/data/element_view.ts): per element the single-bond covalent radius, the
van der Waals radius and the Jmol colour, copied from engine/data/covalent_radii.json (the file the 3D structure builder
uses), so the viewer draws what the engine built. Run: python3 pipeline/db/build_element_view.py"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
src = json.loads((ROOT / "engine" / "data" / "covalent_radii.json").read_text())
rows = []
for el, d in src["elements"].items():
    rows.append(f"  {el}: [{d['r1']}, {d.get('vdw', 2.0)}, '{d['jmol']}'],")
out = (
    "// GENERATED by pipeline/db/build_element_view.py from engine/data/covalent_radii.json. Do not edit.\n"
    "// Per element: [single-bond covalent radius (Pyykko), van der Waals radius (Bondi, else Alvarez), Jmol colour], angstrom.\n"
    "export const ELEMENT_VIEW: Record<string, [number, number, string]> = {\n" + "\n".join(rows) + "\n};\n"
)
(ROOT / "web" / "src" / "data" / "element_view.ts").write_text(out)
print(f"wrote {len(rows)} elements")
