#!/usr/bin/env python3
"""Measured excess molar volumes of binary liquid mixtures (ThermoML 've' category) -> engine/data/excess_volume.json

Redlich-Kister fits, V^E = x_a x_b sum_k A_k (x_a - x_b)^k (cm3 per mole of mixture), of every binary with at least 8 points within
293-303 K spanning x_a 0.3-0.7 (same fitter as build_excess_enthalpy.py).  Pairs without a row add their volumes (ideal mixing).
"""
import json
import sys
from collections import defaultdict
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
from build_excess_enthalpy import elements_ok, rk_fit  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "pipeline" / "cache" / "thermoml" / "ve.jsonl"
OUT = ROOT / "engine" / "data" / "excess_volume.json"


def main():
    groups, names = defaultdict(list), {}
    for line in open(SRC):
        r = json.loads(line)
        if len(r["comp_ids"]) != 2 or "m3/mol" not in r["property"] or r.get("T_K") is None or not 293.15 <= r["T_K"] <= 303.15:
            continue
        c = r["compounds"]
        if len(c) != 2 or not all(x.get("key") and elements_ok(x.get("formula")) for x in c):
            continue
        if r.get("P_kPa") is not None and r["P_kPa"] > 1000:
            continue
        ia, ib = r["comp_ids"]
        xs = r["x"]
        if str(ia) in xs:
            xa = xs[str(ia)]
        elif str(ib) in xs:
            xa = 1.0 - xs[str(ib)]
        else:
            continue
        ka, kb = c[0]["key"], c[1]["key"]
        if ka == kb:
            continue
        if ka > kb:
            ka, kb, xa = kb, ka, 1.0 - xa
            c = [c[1], c[0]]
        if 0 < xa < 1:
            groups[(ka, kb)].append((xa, r["value"] * 1e6, r["T_K"], r["doi"]))
            names[ka], names[kb] = c[0].get("name"), c[1].get("name")
    pairs = []
    for (ka, kb), pts in sorted(groups.items()):
        if len(pts) < 8:
            continue
        x = np.array([p[0] for p in pts]); y = np.array([p[1] for p in pts])
        if x.min() > 0.3 or x.max() < 0.7:
            continue
        coeff, rms = rk_fit(x, y)
        dois = sorted({p[3] for p in pts})
        pairs.append({"a": ka, "b": kb, "A_cm3_mol": [round(float(c), 4) for c in coeff], "T_K": round(float(np.mean([p[2] for p in pts])), 2),
                      "n_points": len(pts), "n_papers": len(dois), "rms_cm3_mol": round(rms, 4), "tier": "tabulated",
                      "source": "NIST/TRC ThermoML Archive: " + ", ".join(dois[:4]) + (" ..." if len(dois) > 4 else ""), "note": f"{names[ka]} (a) + {names[kb]} (b)"})
    old = json.loads((ROOT / "pipeline" / "data" / "excess_volume_hand.json").read_text())["pairs"]
    have = {(p["a"], p["b"]) for p in pairs} | {(p["b"], p["a"]) for p in pairs}
    kept = [dict(p, tier="estimated", source="recalled value (not covered by the ThermoML data)") for p in old if (p["a"], p["b"]) not in have]
    doc = {"model": "Redlich-Kister excess molar volume of binary liquid mixtures: V_E = x_a x_b sum_k A_k (x_a - x_b)^k, cm3 per mole of mixture",
           "tier": "tabulated",
           "source": "Redlich-Kister coefficients fitted (Huber-weighted least squares, number of terms by AICc) to the measured excess molar volumes of the NIST/TRC ThermoML Archive (2020-09-30) within 293-303 K, one row per binary with at least 8 points spanning x_a 0.3-0.7. A pair that is not listed here has no excess volume: the volumes add (ideal) and the phase is labelled so. Generated by pipeline/db/build_excess_volume.py; the earlier recalled rows are kept (tier estimated) only where the data have no pair.",
           "pairs": pairs + kept}
    OUT.write_text(json.dumps(doc, indent=0) + "\n")
    print(len(pairs), "binaries fitted,", len(kept), "hand rows kept; rms median", float(np.median([p["rms_cm3_mol"] for p in pairs])))


main()
