#!/usr/bin/env python3
"""Structures the formula rule of engine/src/structure3d.rs gets wrong -> engine/data/structure_smiles.json

The 3D builder draws a species without a SMILES from its formula (one central atom with the others as ligands). That is wrong
for chains and bridges (thiosulfate S-SO3, peroxodisulfate O3S-O-O-SO3, the polythionates, pyrophosphates, disulfite,
tetraborate) and gives a poor topology for the metal oxo-anions. This script asks PubChem (PUG REST, by name) for the SMILES
of each such ion, checks that PubChem's formula and charge are the species', and writes the rows with CID, InChIKey and the
retrieval date. Nothing in the output is written by hand.

Usage:  python3 pipeline/db/build_structure_smiles.py
"""
import datetime
import json
import re
import sys
import time
import urllib.parse
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "engine" / "data" / "structure_smiles.json"
PUG = "https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/name/{}/property/MolecularFormula,Charge,SMILES,InChIKey/JSON"

# (element formula as the engine writes it, charge, PubChem name)
QUERIES = [
    ("P2O7", -4, "diphosphate(4-)"),
    ("HP2O7", -3, "hydrogen diphosphate"),
    ("H2P2O7", -2, "dihydrogen diphosphate"),
    ("H3P2O7", -1, "trihydrogen diphosphate"),
    ("H4P2O7", 0, "diphosphoric acid"),
    ("S2O3", -2, "thiosulfate(2-)"),
    ("HS2O3", -1, "thiosulfate"),
    ("H2S2O3", 0, "thiosulfuric acid"),
    ("S2O5", -2, "disulfite"),
    ("S2O8", -2, "peroxydisulfate"),
    ("S3O6", -2, "trithionate"),
    ("S4O6", -2, "tetrathionate"),
    ("S5O6", -2, "pentathionate"),
    ("B4O7", -2, "tetraborate"),
    ("N2O", 0, "nitrous oxide"),
    ("Cr2O7", -2, "dichromate"),
    ("CrO4", -2, "chromate"),
    ("HCrO4", -1, "hydrogen chromate"),
    ("MnO4", -1, "permanganate"),
    ("MoO4", -2, "molybdate"),
    ("WO4", -2, "tungstate"),
]


def counts(formula):
    out = {}
    for el, n in re.findall(r"([A-Z][a-z]?)(\d*)", formula):
        out[el] = out.get(el, 0) + (int(n) if n else 1)
    return out


def fetch(name):
    url = PUG.format(urllib.parse.quote(name))
    with urllib.request.urlopen(url, timeout=20) as r:
        return json.load(r)["PropertyTable"]["Properties"]


def main():
    today = datetime.date.today().isoformat()
    rows, missing = [], []
    for formula, charge, name in QUERIES:
        try:
            props = fetch(name)
        except Exception as e:  # noqa: BLE001 - report and continue
            missing.append((formula, charge, name, str(e)))
            continue
        want = counts(formula)
        hit = next((p for p in props if counts(re.sub(r"[+-]\d*$", "", p["MolecularFormula"])) == want and int(p.get("Charge", 0)) == charge), None)
        if hit is None:
            missing.append((formula, charge, name, "no PubChem record with this formula and charge"))
            continue
        rows.append({
            "formula": formula,
            "charge": charge,
            "smiles": hit["SMILES"],
            "cid": hit["CID"],
            "inchikey": hit["InChIKey"],
            "source": f"PubChem CID {hit['CID']} ('{name}'), PUG REST, retrieved {today}",
        })
        time.sleep(0.25)  # PubChem asks for at most 5 requests per second
    doc = {
        "_comment": "Structures (SMILES) of species without one that the formula rule of engine/src/structure3d.rs would draw wrongly "
        "(chains, bridges, metal oxo-anions), keyed by element formula + charge. Generated by pipeline/db/build_structure_smiles.py "
        "from PubChem (tier Tabulated); never written by hand.",
        "rows": rows,
    }
    OUT.write_text(json.dumps(doc, indent=1) + "\n")
    print(len(rows), "rows ->", OUT)
    for m in missing:
        print("not found:", m, file=sys.stderr)


if __name__ == "__main__":
    main()
