#!/usr/bin/env python3
"""Per-element geometry data for the 3D structure builder (engine/src/structure3d.rs) -> engine/data/covalent_radii.json

Columns (all read from the element table of the `mendeleev` package, pm -> Angstrom):
  r1, r2, r3   single-, double-, triple-bond covalent radii: Pyykko & Atsumi, Chem. Eur. J. 15, 186 (2009) (single),
               15, 12770 (2009) (double); Pyykko, Riedel & Patzschke, Chem. Eur. J. 11, 3511 (2005) (triple)
  vdw          van der Waals radius: Bondi, J. Phys. Chem. 68, 441 (1964) where it has one, else Alvarez,
               Dalton Trans. 42, 8617 (2013) (`vdw_src` says which)
  en           Pauling electronegativity (mendeleev `en_pauling`)
  group        IUPAC group (None for the f block)
  jmol         Jmol / CPK display colour (hex), for the viewer

Usage:  python3 pipeline/db/build_covalent_radii.py [path/to/mendeleev/elements.db]
Without a path the installed `mendeleev` package is used; with one, its SQLite data file is read directly (same table).
"""
import json
import sqlite3
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "engine" / "data" / "covalent_radii.json"
MAX_Z = 103


def rows_from_db(path):
    con = sqlite3.connect(f"file:{path}?mode=ro", uri=True)
    cur = con.execute(
        "select atomic_number, symbol, covalent_radius_pyykko, covalent_radius_pyykko_double, covalent_radius_pyykko_triple, "
        "vdw_radius_bondi, vdw_radius_alvarez, en_pauling, group_id, jmol_color from elements where atomic_number <= ? order by atomic_number",
        (MAX_Z,),
    )
    return list(cur)


def rows_from_package():
    from mendeleev import element

    out = []
    for z in range(1, MAX_Z + 1):
        e = element(z)
        out.append((z, e.symbol, e.covalent_radius_pyykko, e.covalent_radius_pyykko_double, e.covalent_radius_pyykko_triple,
                    e.vdw_radius_bondi, e.vdw_radius_alvarez, e.en_pauling, e.group_id, e.jmol_color))
    return out


def a(pm):
    return None if pm is None else round(pm / 100.0, 3)


def main():
    rows = rows_from_db(sys.argv[1]) if len(sys.argv) > 1 else rows_from_package()
    elements = {}
    for z, sym, r1, r2, r3, vb, va, en, grp, jmol in rows:
        if r1 is None:
            continue
        row = {"z": z, "r1": a(r1)}
        if r2 is not None:
            row["r2"] = a(r2)
        if r3 is not None:
            row["r3"] = a(r3)
        if vb is not None:
            row["vdw"], row["vdw_src"] = a(vb), "bondi"
        elif va is not None:
            row["vdw"], row["vdw_src"] = a(va), "alvarez"
        if en is not None:
            row["en"] = round(en, 2)
        if grp is not None:
            row["group"] = int(grp)
        if jmol:
            row["jmol"] = jmol
        elements[sym] = row
    doc = {
        "_comment": "Per-element geometry data of the 3D structure builder (engine/src/structure3d.rs), Angstrom, generated by "
        "pipeline/db/build_covalent_radii.py from the element table of the mendeleev package (tier Tabulated). r1 / r2 / r3: "
        "single-, double- and triple-bond covalent radii of Pyykko & Atsumi, Chem. Eur. J. 15, 186 and 12770 (2009) and Pyykko, "
        "Riedel & Patzschke, Chem. Eur. J. 11, 3511 (2005). vdw: Bondi, J. Phys. Chem. 68, 441 (1964), else Alvarez, Dalton "
        "Trans. 42, 8617 (2013) (vdw_src). en: Pauling electronegativity. group: IUPAC group (absent for the f block). jmol: "
        "Jmol display colour.",
        "elements": elements,
    }
    OUT.write_text(json.dumps(doc, indent=1) + "\n")
    print(len(elements), "elements ->", OUT)


if __name__ == "__main__":
    main()
