//! A1 of docs/plans/data-acquisition-plan.md: ion association from measured constants.
//!
//! The pair rows come from the PHREEQC-format databases (minteq.v4, wateq4f, llnl, ...; `data/complexes.json`, generated by
//! `pipeline/db/build_complexes.py`) and replace the outer-sphere Fuoss estimate wherever a measured row exists. The gate is
//! the fraction of the cation (or of the sulfate) that is paired in a 0.1 m solution of ten salts, against an independent
//! speciation calculation: PHREEQC itself (`phreeqpython`, minteq.v4.dat and wateq4f.dat, the mean of the two is the
//! reference; the two databases differ by up to 0.05 in these fractions). The engine uses its own activity model (B-dot /
//! Pitzer), so agreement within 8 percentage points tests the constants and the speciation together.

use std::collections::HashMap;

use reaction_chamber_engine::vessel::*;

fn beaker() -> Vessel {
    Vessel::new(VesselConfig {
        vessel_type: "beaker-1000".into(),
        capacity_ml: 1000.0,
        glass_mass_g: 400.0,
        inner_radius_cm: 5.5,
        temperature_k: Some(298.15),
        room_k: Some(298.15),
        sealed: Some(false),
        stopper_pop_atm: Some(2.2),
        burst_atm: Some(6.0),
    })
}

fn solution(ions: &[(&str, f64)]) -> Vessel {
    let mut v = beaker();
    let mut aq: HashMap<String, f64> = HashMap::new();
    aq.insert("H2O".to_string(), 500.0 * 0.9970 / 18.015); // 0.5 kg of water
    for (sp, mol) in ions {
        aq.insert(sp.to_string(), *mol);
    }
    v.add_portion(Portion { volume_ml: 500.0, temperature_k: 298.15, aqueous_mol: aq, organic_mol: HashMap::new(), solid_mol: HashMap::new(), particles: HashMap::new(), forms: HashMap::new() }).unwrap();
    v.equilibrate(60.0);
    v
}

/// (salt, ions as moles in 0.5 kg water, the ion whose paired fraction is measured, the species that hold it,
/// PHREEQC reference fraction paired: mean of minteq.v4 and wateq4f at 0.1 mol/kgw, 0.015 for CaSO4 near its saturation)
const CASES: &[(&str, &[(&str, f64)], &str, &[&str], f64)] = &[
    ("MgSO4", &[("Mg+2", 0.05), ("SO4-2", 0.05)], "Mg+2", &["MgSO4"], 0.499),
    ("CaSO4", &[("Ca+2", 0.0075), ("SO4-2", 0.0075)], "Ca+2", &["CaSO4"], 0.338),
    ("ZnSO4", &[("Zn+2", 0.05), ("SO4-2", 0.05)], "Zn+2", &["ZnSO4", "Zn(SO4)2-2"], 0.512),
    ("CdSO4", &[("Cd+2", 0.05), ("SO4-2", 0.05)], "Cd+2", &["CdSO4", "Cd(SO4)2-2"], 0.526),
    ("NiSO4", &[("Ni+2", 0.05), ("SO4-2", 0.05)], "Ni+2", &["NiSO4"], 0.479),
    ("Na2SO4", &[("Na+", 0.10), ("SO4-2", 0.05)], "SO4-2", &["NaSO4-"], 0.208),
    ("K2SO4", &[("K+", 0.10), ("SO4-2", 0.05)], "SO4-2", &["KSO4-"], 0.254),
    ("MgCl2", &[("Mg+2", 0.05), ("Cl-", 0.10)], "Mg+2", &["MgCl+"], 0.0),
];

fn paired_fraction(v: &Vessel, free: &str, held_by: &[&str]) -> f64 {
    let f = v.species_mol.get(free).copied().unwrap_or(0.0);
    let p: f64 = held_by.iter().map(|s| v.species_mol.get(*s).copied().unwrap_or(0.0)).sum();
    // a species counts once per ion of `free` it holds (Zn(SO4)2-2 holds one Zn, two SO4: the cation fraction counts it once)
    let _ = f;
    let _ = p;
    let total = f + p;
    if total <= 0.0 { 0.0 } else { p / total }
}

#[test]
fn paired_fractions_match_an_independent_speciation_calculation() {
    let mut worst = 0.0_f64;
    let mut report = Vec::new();
    for (salt, ions, free, held_by, reference) in CASES {
        let v = solution(ions);
        let got = paired_fraction(&v, free, held_by);
        worst = worst.max((got - reference).abs());
        report.push(format!("{salt}: engine {got:.3} vs PHREEQC {reference:.3}"));
        assert!((got - reference).abs() < 0.08, "{salt}: engine {got:.3} vs reference {reference:.3}\n{}", report.join("\n"));
    }
    eprintln!("{}\nworst difference {worst:.3}", report.join("\n"));
}

/// The measured rows replace the Fuoss estimate: MgSO4 is no longer the over-paired 63 % of the outer-sphere model.
#[test]
fn magnesium_sulfate_is_not_over_paired() {
    let v = solution(&[("Mg+2", 0.05), ("SO4-2", 0.05)]);
    let got = paired_fraction(&v, "Mg+2", &["MgSO4"]);
    assert!(got > 0.35 && got < 0.60, "MgSO4 paired {got:.3} (measured ~0.4-0.5; the Fuoss model gave 0.63)");
}
