//! P3 of docs/plans/data-acquisition-plan.md: Pitzer parameters with their temperature functions.
//!
//! `data/ion_interactions.json` (`pitzer_binary`) now holds the 54 binary parameter sets of PHREEQC's pitzer.dat (beta0, beta1,
//! beta2 for 2:2 electrolytes, C^phi, each with the six-term temperature function), generated by `pipeline/db/parse_pitzer.py`.
//! The gate compares the osmotic coefficient of four single-salt solutions (NaCl, KCl, Na2SO4, CaCl2; MgSO4 is left out on purpose: its Pitzer set already holds the ion pair, which the engine models explicitly from the measured row) at 25, 60 and 100 C and 0.1-2 mol/kg with the
//! water activity PHREEQC itself computes (`pipeline/make_pitzer_reference.py`: phreeqpython, same parameter file; an
//! independent implementation of the equations and of A_phi(T)), within 0.011.

use std::collections::HashMap;

use reaction_chamber_engine::activity::ionic_ln_water_activity;

#[derive(serde::Deserialize)]
struct Ref {
    rows: Vec<Row>,
}
#[derive(serde::Deserialize)]
struct Row {
    salt: String,
    t_c: f64,
    m: f64,
    phi: f64,
}

fn ions_of(salt: &str) -> (Vec<(&'static str, f64)>, f64) {
    match salt {
        "NaCl" => (vec![("Na+", 1.0), ("Cl-", 1.0)], 2.0),
        "KCl" => (vec![("K+", 1.0), ("Cl-", 1.0)], 2.0),
        "Na2SO4" => (vec![("Na+", 2.0), ("SO4-2", 1.0)], 3.0),
        "CaCl2" => (vec![("Ca+2", 1.0), ("Cl-", 2.0)], 3.0),
        other => panic!("{other}"),
    }
}

fn engine_phi(salt: &str, m: f64, t_k: f64) -> f64 {
    let (ions, nu) = ions_of(salt);
    let mut sp: HashMap<String, f64> = HashMap::new();
    sp.insert("H2O".into(), 1.0 / 0.01801528);
    for (i, n) in ions {
        sp.insert(i.into(), n * m);
    }
    -ionic_ln_water_activity(&sp, t_k) / (0.01801528 * nu * m)
}

#[test]
fn osmotic_coefficients_follow_the_evaluated_values_over_temperature() {
    let r: Ref = serde_json::from_str(include_str!("data/pitzer_osmotic_reference.json")).unwrap();
    let mut worst: (f64, String) = (0.0, String::new());
    let mut bad = Vec::new();
    for row in &r.rows {
        let phi = engine_phi(&row.salt, row.m, row.t_c + 273.15);
        let d = (phi - row.phi).abs();
        if d > worst.0 {
            worst = (d, format!("{} {} C {} m: {:.4} vs {:.4}", row.salt, row.t_c, row.m, phi, row.phi));
        }
        if d > 0.011 {
            bad.push(format!("{} {} C {} m: engine {:.4} vs PHREEQC {:.4}", row.salt, row.t_c, row.m, phi, row.phi));
        }
    }
    eprintln!("worst: {}", worst.1);
    assert!(bad.is_empty(), "{} of {} points off by more than 0.011:\n{}", bad.len(), r.rows.len(), bad.join("\n"));
}

/// NaCl at 25 C, 1 mol/kg: the evaluated osmotic coefficient is 0.9373 (Archer 1992 / Pitzer-Silvester).
#[test]
fn sodium_chloride_at_25_c_is_the_textbook_value() {
    let phi = engine_phi("NaCl", 1.0, 298.15);
    assert!((phi - 0.9373).abs() < 0.005, "phi {phi}");
}
