//! Appearance from optical records (Stage 10).
//!
//! Every visible quantity is derived from per-species *optical records* (`db::record::Optics`: absorption bands per
//! solvent, band gaps, gas cross-sections, molar refractions, each with tier and source) and from the vessel state
//! (phase compositions, particle populations, temperature):
//!
//! - `cie`: the 380-780 nm grid (41 bins) and colorimetry (CIE 1931 CMFs x D65 -> linear sRGB);
//! - `records`: the seed rows (`data/optics_seed.json`, generated by `pipeline/db/build_optics_seed.py`) and the lookup
//!   order store record -> seed;
//! - `ligand_field`: Tanabe-Sugano d-d bands of first-row transition-metal complexes (Estimated);
//! - `solution`: per-phase absorbance from the records of its species *in that phase's solvent*;
//! - `fallback`: the single Speculative RGB -> spectrum inversion (neat coloured liquids, solids known only by a colour);
//! - `solid`: Kubelka-Munk reflectance of solids from band gap and inherited ion chromophores;
//! - `scatter`: per-bin Mie / Rayleigh-Gans turbidity of suspended solids;
//! - `gas`: gas cross-sections x column density, buoyancy and fuming;
//! - `flame`: flame-test emission from atomic lines (Boltzmann + Saha) and molecular bands.

pub mod cie;
pub mod fallback;
pub mod flame;
pub mod gas;
pub mod ligand_field;
pub mod records;
pub mod scatter;
pub mod solid;
pub mod solution;

pub use cie::{bin_nm, delta_e, spectrum_to_rgb, spectrum_to_rgb_clamped, to_srgb, transmitted_linear_rgb, Spectrum, BIN_NM0, BIN_STEP_NM, N_BINS};

/// JSON of `OpticsTables` (see web/src/types/sim.ts).
pub fn tables_json() -> String {
    serde_json::json!({
        "n_bins": N_BINS,
        "bin_nm0": BIN_NM0,
        "bin_step_nm": BIN_STEP_NM,
        "rgb_weights": cie::rgb_weights_flat(),
        // hash of every optical datum and model table: caches of colours derived from the optics data key on it
        "data_version": format!("{:016x}", records::data_hash())
    })
    .to_string()
}
