//! Measured rate constants of whole reactions (`data/rates_measured.json`). They outrank every estimate.
//!
//! * Organic steps (generated from the reaction templates): an entry names its reactants and products by SMILES and the
//!   template (or `*` for any); it is turned into a structural rate-store key (`rate_store::reaction_key`) with the solvent
//!   class appended, so the network generator finds it before the template rule. A measured k without an activation energy
//!   takes its temperature dependence from the rule's Ea.
//! * Homogeneous electron transfer between two couples (discovered by `gem`): an entry names the four species ids and the
//!   species its rate law is written for (`-d[rate_of]/dt = k [donor][acceptor] [H+]^h_order`); the vessel converts it to
//!   its own stoichiometry (`Vessel::redox_homogeneous_rate`), in place of the Marcus cross relation.
//!
//! `rates_measured.json` is generated by `pipeline/db/build_rates_measured.py` from `pipeline/data/rates_measured.csv`: organic
//! rows only when they were read from their source (`status = verified`), redox rows with their `verification`. Tests and the
//! app can add entries at run time (`register_organic`, `register_redox`).

use std::collections::HashMap;
use std::sync::{Mutex, OnceLock};

use serde::{Deserialize, Serialize};

use crate::physics::R_GAS;
use crate::rate_store::{self, RateEntry};
use crate::types::ProvenanceTier;

fn default_t_k() -> f64 {
    298.15
}

/// A single term in an empirical rate law: k at t_k, with activation energy and species orders.
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
pub struct RateLawTerm {
    pub k: f64,
    #[serde(default = "default_t_k")]
    pub t_k: f64,
    #[serde(default)]
    pub ea_kj_mol: Option<f64>,
    #[serde(default)]
    pub orders: HashMap<String, f64>,
}

impl RateLawTerm {
    /// The rate constant of this term at `t_k`.
    pub fn k_at(&self, t_k: f64) -> f64 {
        match self.ea_kj_mol {
            Some(ea) => self.k * (-(ea * 1000.0) / R_GAS * (1.0 / t_k.max(1.0) - 1.0 / self.t_k)).exp(),
            None => self.k,
        }
    }
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct OrganicRate {
    /// Template id plus `_variant` when the variant has a tag, or `*` for any template.
    #[serde(default = "any_template")]
    pub template: String,
    pub reactants: Vec<String>,
    pub products: Vec<String>,
    #[serde(default)]
    pub k_m_s: f64,
    #[serde(default = "default_t_k")]
    pub t_k: f64,
    #[serde(default)]
    pub ea_kj_mol: Option<f64>,
    #[serde(default = "water")]
    pub solvent_class: String,
    #[serde(default)]
    pub terms: Vec<RateLawTerm>,
    pub source: String,
}

impl OrganicRate {
    pub fn all_terms(&self) -> Vec<RateLawTerm> {
        if !self.terms.is_empty() {
            self.terms.clone()
        } else {
            vec![RateLawTerm {
                k: self.k_m_s,
                t_k: self.t_k,
                ea_kj_mol: self.ea_kj_mol,
                orders: HashMap::new(),
            }]
        }
    }
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
pub struct RedoxRate {
    pub donor: String,
    /// The donor's oxidised form; empty = any product (a rate law measured as the loss of the reactants, whatever they
    /// turn into, governs every pathway of the pair: `Vessel::step_redox` gives it to the most favourable one only).
    #[serde(default)]
    pub donor_product: String,
    pub acceptor: String,
    #[serde(default)]
    pub acceptor_product: String,
    /// The species whose loss rate the measured rate law gives.
    pub rate_of: String,
    #[serde(default)]
    pub k_m_s: f64,
    #[serde(default = "default_t_k")]
    pub t_k: f64,
    #[serde(default)]
    pub ea_kj_mol: Option<f64>,
    /// Order in H+ of the measured rate law (0 when it has none).
    #[serde(default)]
    pub h_order: f64,
    #[serde(default)]
    pub terms: Vec<RateLawTerm>,
    pub source: String,
    /// `verified` (the value was read from `source`) or `recalled` (written from memory, not checked against it); absent =
    /// recalled. A recalled law replaces only the estimate of the Marcus cross relation and is reported as such.
    #[serde(default)]
    pub verification: Option<String>,
}

impl RedoxRate {
    /// True when the value was read from its source.
    pub fn is_verified(&self) -> bool {
        self.verification.as_deref() == Some("verified")
    }

    pub fn all_terms(&self) -> Vec<RateLawTerm> {
        if !self.terms.is_empty() {
            self.terms.clone()
        } else {
            let mut orders = HashMap::new();
            if self.h_order != 0.0 {
                orders.insert(crate::db::seed::PROTON.to_string(), self.h_order);
            }
            vec![RateLawTerm {
                k: self.k_m_s,
                t_k: self.t_k,
                ea_kj_mol: self.ea_kj_mol,
                orders,
            }]
        }
    }

    /// The entry applies to this electron transfer (an empty product matches any).
    pub fn matches(&self, donor: &str, donor_product: &str, acceptor: &str, acceptor_product: &str) -> bool {
        self.donor == donor
            && self.acceptor == acceptor
            && (self.donor_product.is_empty() || self.donor_product == donor_product)
            && (self.acceptor_product.is_empty() || self.acceptor_product == acceptor_product)
    }

    /// Products named: the entry covers one pathway only.
    pub fn product_specific(&self) -> bool {
        !self.donor_product.is_empty() && !self.acceptor_product.is_empty()
    }

    /// The rate constant at `t_k` (Arrhenius from the measured Ea when there is one, else the value at the measured T).
    pub fn k_at(&self, t_k: f64) -> f64 {
        match self.ea_kj_mol {
            Some(ea) => self.k_m_s * (-(ea * 1000.0) / R_GAS * (1.0 / t_k.max(1.0) - 1.0 / self.t_k)).exp(),
            None => self.k_m_s,
        }
    }
}

#[derive(Deserialize)]
struct File {
    #[serde(default)]
    organic: Vec<OrganicRate>,
    #[serde(default)]
    redox: Vec<RedoxRate>,
}

fn any_template() -> String {
    "*".to_string()
}

fn water() -> String {
    "water".to_string()
}

fn redox_table() -> &'static Mutex<Vec<RedoxRate>> {
    static T: OnceLock<Mutex<Vec<RedoxRate>>> = OnceLock::new();
    T.get_or_init(|| Mutex::new(Vec::new()))
}

/// Loads the shipped table once: organic entries into the rate store, redox entries into the redox table.
pub fn ensure_loaded() {
    static LOADED: OnceLock<()> = OnceLock::new();
    LOADED.get_or_init(|| {
        let file: File = serde_json::from_str(include_str!("../data/rates_measured.json")).expect("rates_measured.json is valid");
        register_organic(&file.organic);
        register_redox(file.redox);
    });
}

/// The rate-store entry of a measured organic rate, or None when a SMILES does not parse.
pub fn organic_entry(r: &OrganicRate) -> Option<RateEntry> {
    let parse = |v: &[String]| v.iter().map(|s| crate::smiles::parse(s)).collect::<Option<Vec<_>>>();
    let (rm, pm) = (parse(&r.reactants)?, parse(&r.products)?);
    let key = rate_store::reaction_key(&r.template, &rm.iter().collect::<Vec<_>>(), &pm.iter().collect::<Vec<_>>());
    let terms = r.all_terms();
    let (a, ea, _from_rule, k_ref, t_ref) = if terms.len() == 1 {
        let t0 = &terms[0];
        match t0.ea_kj_mol {
            Some(ea) => (t0.k * (ea * 1000.0 / (R_GAS * t0.t_k)).exp(), ea * 1000.0, false, None, None),
            None => (0.0, 0.0, true, Some(t0.k), Some(t0.t_k)),
        }
    } else {
        (0.0, 0.0, false, None, None)
    };
    Some(RateEntry {
        key: rate_store::with_solvent(&key, &r.solvent_class),
        a,
        ea_j_mol: ea,
        tier: ProvenanceTier::Tabulated,
        source: format!(
            "measured: {} in {} ({})",
            if terms.len() == 1 {
                format!("k = {:.3e} at {:.1} K", terms[0].k, terms[0].t_k)
            } else {
                format!("{}-term rate law", terms.len())
            },
            r.solvent_class, r.source
        ),
        per_reaction: true,
        k_ref,
        t_ref_k: t_ref,
        terms: if terms.len() > 1 { terms } else { Vec::new() },
    })
}

/// Adds measured organic rates to the rate store; returns how many changed it.
pub fn register_organic(rows: &[OrganicRate]) -> usize {
    rate_store::register(rows.iter().filter_map(organic_entry).collect())
}

/// Adds or replaces measured electron-transfer rates (same four species = same entry).
pub fn register_redox(rows: Vec<RedoxRate>) {
    let mut t = redox_table().lock().unwrap_or_else(|e| e.into_inner());
    for r in rows {
        let terms = r.all_terms();
        if terms.is_empty() || terms.iter().any(|tm| !tm.k.is_finite() || tm.k <= 0.0 || tm.t_k <= 0.0) {
            continue;
        }
        t.retain(|x| !(x.donor == r.donor && x.donor_product == r.donor_product && x.acceptor == r.acceptor && x.acceptor_product == r.acceptor_product));
        t.push(r);
    }
}

/// The measured rate of the electron transfer donor -> donor_product, acceptor -> acceptor_product: an entry naming both
/// products first, else one naming fewer.
pub fn redox_rate(donor: &str, donor_product: &str, acceptor: &str, acceptor_product: &str) -> Option<RedoxRate> {
    ensure_loaded();
    let t = redox_table().lock().unwrap_or_else(|e| e.into_inner());
    let mut hits: Vec<&RedoxRate> = t.iter().filter(|x| x.matches(donor, donor_product, acceptor, acceptor_product)).collect();
    // the most specific entry wins (both products named, then one, then none)
    hits.sort_by_key(|x| std::cmp::Reverse((!x.donor_product.is_empty()) as u8 + (!x.acceptor_product.is_empty()) as u8));
    hits.first().map(|x| (*x).clone())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn shipped_table_parses() {
        let _: File = serde_json::from_str(include_str!("../data/rates_measured.json")).unwrap();
    }

    #[test]
    fn measured_arrhenius_scales_with_temperature() {
        let r = RedoxRate { donor: "a".into(), donor_product: "b".into(), acceptor: "c".into(), acceptor_product: "d".into(),
            rate_of: "a".into(), k_m_s: 10.0, t_k: 298.15, ea_kj_mol: Some(50.0), h_order: 0.0, terms: Vec::new(), source: "t".into(), verification: None };
        assert!((r.k_at(298.15) - 10.0).abs() < 1e-9);
        assert!(r.k_at(308.15) > 18.0 && r.k_at(308.15) < 21.0);
    }
}
